#!/bin/sh
#
# Start stress-ng
#

start() {
	start-stop-daemon -S -q -b -m -p /var/run/stress_cpu.pid --exec \
		/usr/bin/stress-ng -- -q --cpu 2 --cpu-load 80 --taskset 0,1
}
stop() {
	start-stop-daemon -K -q -p /var/run/stress_cpu.pid
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
