#!/bin/sh
#
# Start stress-ng
#

start() {
	start-stop-daemon -S -q -b -m -p /var/run/dd_mmc.pid --exec \
		dd -- if=/dev/mmcblk0 of=/dev/null
}
stop() {
	start-stop-daemon -K -q -p /var/run/dd_mmc.pid
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
